SELECT EXTRACT(YEAR FROM SYSDATE)"AÑO TRIBUTARIO", TO_CHAR(NUMRUN_EMP) ||'-'|| TO_CHAR(DVRUN_EMP) "RUN EMPLEADO",PNOMBRE_EMP ||' ' || SNOMBRE_EMP ||' '||APPATERNO_EMP ||' '|| APMATERNO_EMP  "NOMBRE EMPLEADO", CASE 
WHEN MONTHS_BETWEEN (TRUNC(SYSDATE,'YYYY'),FECHA_CONTRATO)>=12
THEN 12 ELSE MONTHS_BETWEEN (TRUNC(SYSDATE,'YYYY'),FECHA_CONTRATO) END AS "MESES TRABAJADOS EN EL AÑO", TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE,'YYYY'),FECHA_CONTRATO)/12) "AÑOS TRABAJADOS",
SUELDO_BASE "SUELDO BASE MENSUAL", SUELDO_BASE*12 "SUELDO BASE ANUAL", TRUNC(SUELDO_BASE*12*(TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE,'YYYY'),FECHA_CONTRATO)/12))/100) "BONO POR AÑOS ANUAL",
TRUNC(12*SUELDO_BASE*0.12) "MOVILIZACION ANUAL", TRUNC(12*SUELDO_BASE*0.20) "COLACION ANUAL",
TRUNC(SUELDO_BASE*12 + TRUNC(SUELDO_BASE*12*(TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE,'YYYY'),FECHA_CONTRATO)/12))/100) + 12*SUELDO_BASE*0.12 + 12*SUELDO_BASE*0.20) "SUELDO BRUTO ANUAL",
SUELDO_BASE*12 + TRUNC(SUELDO_BASE*12*(TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE,'YYYY'),FECHA_CONTRATO)/12))/100) "RENTA IMPONIBLE ANUAL"
FROM EMPLEADO
ORDER BY NUMRUN_EMP;